'use client'
import { useState } from 'react'
import { useRouter } from 'next/navigation'
import type { ContentItem, ContentStatus } from '@/lib/types'
import { nextStatuses, STATUS_LABEL } from '@/lib/domain/status'
import { saveCaption, changeStatus } from '@/app/(app)/actions'
import PlatformBadge from './PlatformBadge'
import StatusBadge from './StatusBadge'

export default function ContentDrawer({ item, onClose }: { item: ContentItem; onClose: () => void }) {
  const router = useRouter()
  const [caption, setCaption] = useState(item.caption ?? '')

  const next = nextStatuses(item.content_status)

  return (
    <div className="fixed inset-0 z-40 flex justify-end">
      <button
        type="button"
        aria-label="Close"
        onClick={onClose}
        className="absolute inset-0 bg-inverse-surface/20 backdrop-blur-[1px] animate-overlay-in"
      />
      <aside className="relative w-[440px] max-w-[90vw] bg-surface h-full shadow-elevated flex flex-col animate-drawer-in">
        {/* Header */}
        <div className="flex items-center justify-between px-6 h-14 border-b border-[#ebebf0]">
          <div className="text-sm font-medium text-on-surface-variant">Content Details</div>
          <button
            type="button"
            onClick={onClose}
            className="w-8 h-8 rounded-lg flex items-center justify-center text-outline hover:bg-surface-container-low hover:text-on-surface transition-colors"
          >
            <span className="material-symbols-outlined">close</span>
          </button>
        </div>

        {/* Content */}
        <div className="flex-1 overflow-y-auto custom-scrollbar px-6 py-4 space-y-6">
          <div className="flex items-center gap-2">
            <PlatformBadge platform={item.platform} />
            <StatusBadge status={item.content_status} />
          </div>

          <h2 className="text-[24px] font-semibold tracking-[-0.02em] leading-[1.2] text-on-surface">
            {item.title}
          </h2>

          {/* Caption editor */}
          <div>
            <label className="block label-caps text-on-surface-variant mb-2">Caption</label>
            <textarea
              value={caption}
              onChange={(e) => setCaption(e.target.value)}
              onBlur={() => { void saveCaption(item.id, caption); router.refresh() }}
              rows={5}
              placeholder="Write your caption here…"
              className="w-full rounded-lg border border-[#ebebf0] px-3 py-2 text-[15px] leading-[1.6] text-on-surface placeholder:text-outline focus:outline-none focus:border-primary focus:ring-1 focus:ring-primary transition-all resize-none"
            />
          </div>

          {/* Publish date */}
          <div>
            <div className="label-caps text-on-surface-variant mb-1">Publish Date</div>
            <div className="text-[15px] text-on-surface">{item.publish_date ?? 'Not scheduled'}</div>
          </div>

          {/* Insight reference */}
          <div>
            <div className="label-caps text-on-surface-variant mb-1">Linked Insight</div>
            <div className="text-[15px] text-outline">{item.insight_id ?? 'None'}</div>
          </div>

          {/* AI provenance */}
          {item.generated_by && (
            <div>
              <div className="label-caps text-on-surface-variant mb-1">Generated By</div>
              <div className="flex items-center gap-1.5 text-[15px] text-primary">
                <span
                  className="material-symbols-outlined text-sm"
                  style={{ fontVariationSettings: "'FILL' 1" }}
                >
                  auto_awesome
                </span>
                {item.generated_by}
              </div>
            </div>
          )}
        </div>

        {/* Status transition buttons */}
        {next.length > 0 && (
          <div className="px-6 py-4 flex gap-2 border-t border-[#ebebf0]">
            {next.map((to: ContentStatus) => (
              <button
                key={to}
                type="button"
                onClick={() => { void changeStatus(item.id, item.content_status, to); router.refresh() }}
                className="flex-1 rounded-lg bg-primary px-4 py-2.5 text-sm font-medium text-white hover:bg-primary-container transition-all active:scale-[0.98]"
              >
                {STATUS_LABEL[to]}
              </button>
            ))}
          </div>
        )}
      </aside>
    </div>
  )
}
